package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.geometry.Orientation;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class KunstwerkProfilController implements Initializable {
	private int kunstwerk;
	private String nutzer;
	@FXML
	private Label labelKWName;
	@FXML
	private Label labelCYear;
	@FXML
	private Label labelArtstyle;
	@FXML
	private TableView<String> tview_Abdruck;
	@FXML
	private TableColumn breiteColumn;
	@FXML
	private TableColumn hoeheColumn;
	@FXML
	private TableColumn preisColumn;
	@FXML
	private TableColumn idColumn;
	@FXML
	private Button btnBestellen;
	@FXML
	private Label labelStandort;
	@FXML
	private TableView<KunstwerkBewertung> tview_Bewertung;
	@FXML
	private TableColumn<KunstwerkBewertung, Integer> bewertungColumn;
	@FXML
	private TableColumn<KunstwerkBewertung, String> kommentarColumn;
	@FXML
	private TableColumn<KunstwerkBewertung, String> userColumn;
	@FXML
	private ListView<Integer> lviewWertung;
	@FXML
	private TextField tareaWertung;
	@FXML
	private Button btnSendWertung;

	public ObservableList<Integer> wertungen = FXCollections.observableArrayList (1,2,3,4,5,6,7,8,9,10);


	// Constructor: Mal wieder, um Werte zu übergeben.
	public KunstwerkProfilController(int kunstwerk, String nutzer) {
		this.kunstwerk = kunstwerk;
		this.nutzer = nutzer;
	}

	// Event Listener on Button[#btnBestellen].onAction
	@FXML
	public void handleOrderBtnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSendWertung].onAction
	@FXML
	public void handleSendBtnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		lviewWertung.setOrientation(Orientation.HORIZONTAL);
		lviewWertung.setItems(wertungen);

	}
}
