package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.Tab;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class SearchController implements Initializable{
	@FXML
	private TextField tfieldMuseumFilter;
	@FXML
	private ComboBox cboxMuseumFilter;
	@FXML
	private TableView tviewMuseum;
	@FXML
	private TableColumn museumnameColumn;
	@FXML
	private TableColumn museumcityColumn;
	@FXML
	private Button btnMuseumDetails;
	@FXML
	private Tab cboxArtistFilter;
	@FXML
	private TextField tfieldArtistFilter;
	@FXML
	private TableView tviewArtists;
	@FXML
	private TableColumn artistfnColumn;
	@FXML
	private TableColumn artistlnColumn;
	@FXML
	private TableColumn artistunameColumn;
	@FXML
	private Tab cboxArtworkFilter;
	@FXML
	private TextField tfieldArtworkFilter;
	@FXML
	private TableView tviewArtworks;
	@FXML
	private TableColumn artworknameColumn;
	@FXML
	private TableColumn artstyleColumn;
	@FXML
	private Tab cboxCollectionFilter;
	@FXML
	private TextField tfieldCollectionFilter;
	@FXML
	private TableView tviewCollections;
	@FXML
	private TableColumn colnameColumn;
	@FXML
	private TableColumn colplaceColumn;

	// Event Listener on Button[#btnMuseumDetails].onAction
	@FXML
	public void showDetails(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub

	}
}
